# Generated by Django 5.2.17 on 2026-09-30 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_document_simulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.UUIDField()),
                ('source', models.CharField(max_length=80)),
                ('target_url', models.URLField()),
                ('next_file', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.CharField(blank=True, max_length=250)),
                ('result', models.JSONField(default=dict)),
                ('lease_until', models.DateTimeField(null=True)),
                ('synced_at', models.DateTimeField(null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='portal.application')),
            ],
        ),
    ]
