# Generated by Django 5.2.17 on 2026-09-30 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=80)),
                ('folio', models.CharField(max_length=40)),
                ('manifest', models.JSONField()),
                ('ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=60)),
                ('digest', models.CharField(max_length=64)),
                ('content', models.BinaryField()),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='receiver.dossier')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('proteccion_civil', 'Protección Civil'), ('obras_publicas', 'Obras Públicas'), ('ecologia', 'Ecología')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('proteccion_civil', 'Protección Civil'), ('obras_publicas', 'Obras Públicas'), ('ecologia', 'Ecología')], max_length=30)),
                ('outcome', models.CharField(choices=[('approved', 'Aprobada'), ('rejected', 'Rechazada')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='receiver.dossier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dossier', 'area'), name='one_decision_per_area')],
            },
        ),
    ]
